global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8000']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:9104']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 