version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --bind-address=0.0.0.0
      - --skip-ssl
      - --performance_schema=off
      - --table_definition_cache=200
      - --table_open_cache=128
      - --innodb_buffer_pool_size=128M
      - --max_connections=100
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
        reservations:
          memory: 200M
    logging:
      options:
        max-size: "5m"
        max-file: "2"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build: .
    container_name: spring-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: aws
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JAVA_OPTS: -Xmx300m -Xms300m
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 400M
        reservations:
          memory: 300M
    logging:
      options:
        max-size: "5m"
        max-file: "2"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge 