package com.example.dataloader;

import com.example.entity.CheckCard;
import com.example.repository.CheckCardRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class CheckCardDataLoader implements CommandLineRunner {
    private final CheckCardRepository checkCardRepository;

    public CheckCardDataLoader(CheckCardRepository checkCardRepository) {
        this.checkCardRepository = checkCardRepository;
    }

    @Override
    public void run(String... args) {
        checkCardRepository.save(new CheckCard(null, "ONE 체크카드", "케이뱅크", "https://www.card-gorilla.com/card/detail/2749", "https://d1c5n4ri2guedi.cloudfront.net/card/2749/card_img/39370/2749card_2.png", "['최대: 1.2%캐시백(무제한)', '자주 쓰는 곳에서: 7%캐시백(월 최대 25,000원)', '3번 결제할 때마다: 1,000원캐시백(무제한)', ': 해외겸용 없음', '전월실적: 없음', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "노리2 체크카드(KB Pay)", "KB국민카드", "https://www.card-gorilla.com/card/detail/2422", "https://d1c5n4ri2guedi.cloudfront.net/card/2422/card_img/27141/2422card.png", "['커피, 모바일, 문화: 10%할인', '뷰티, 편의점: 5%할인', 'KB Pay: 2%추가 할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': VISAMastercard']"));
        checkCardRepository.save(new CheckCard(null, "토스뱅크 체크카드", "토스뱅크", "https://www.card-gorilla.com/card/detail/2269", "https://d1c5n4ri2guedi.cloudfront.net/card/2269/card_img/40299/2269card_1.png", "['일상 속 7가지 영역: 월 최대 35,000원캐시백', '온라인 결제 7가지 영역: 월 최대 14,000원캐시백', '국내 온·오프라인 어디서나: 0.3%캐시백', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 Deep Dream 체크(미니언즈)", "신한카드", "https://www.card-gorilla.com/card/detail/646", "https://d1c5n4ri2guedi.cloudfront.net/card/646/card_img/21410/646card.png", "['모두드림: 0.2%적립', '더해드림: 0.6%적립', '챙겨드림: 1.0%적립', ': 해외겸용 없음', '전월실적: 없음', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "네이버페이 머니 하나 체크카드", "하나카드", "https://www.card-gorilla.com/card/detail/2432", "https://d1c5n4ri2guedi.cloudfront.net/card/2432/card_img/27295/2432card.png", "['네이버페이: 1.2%포인트 적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 25만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "네이버페이 우리카드 체크", "우리카드", "https://www.card-gorilla.com/card/detail/588", "https://d1c5n4ri2guedi.cloudfront.net/card/588/card_img/21345/588card.png", "['네이버페이: 1%적립', '공항라운지: 무료이용', '해외수수료: 면제서비스', ': 국내전용 5,000원 해외겸용 5,000원', '전월실적: 없음', ': BCMastercard']"));
        checkCardRepository.save(new CheckCard(null, "카카오페이 신한 체크카드", "신한카드", "https://www.card-gorilla.com/card/detail/286", "https://d1c5n4ri2guedi.cloudfront.net/card/286/card_img/20508/286card.png", "['카카오페이: 2%적립', '대중교통: 3%적립', 'CGV 최대: 3천원적립', ': 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "트래블러스 체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/2691", "https://d1c5n4ri2guedi.cloudfront.net/card/2691/card_img/33455/2691card_2.png", "['해외 이용 수수료: 면제', '철도: 5,000원할인', '전국맛집: 5,000원할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "노리체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/348", "https://d1c5n4ri2guedi.cloudfront.net/card/348/card_img/20581/348card.png", "['대중교통: 10%청구할인', '이동통신요금: 2,500원환급할인', 'CGV: 35%환급할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': VISAMastercardUnionPay']"));
        checkCardRepository.save(new CheckCard(null, "더나은 체크카드", "MG새마을금고", "https://www.card-gorilla.com/card/detail/2601", "https://d1c5n4ri2guedi.cloudfront.net/card/2601/card_img/31113/2601card.png", "['간편결제: 20%할인', '온라인쇼핑: 20%할인', '커피전문점: 20%할인', ': 해외겸용 없음', '전월실적: 30만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "네이버페이 머니카드", "네이버페이", "https://www.card-gorilla.com/card/detail/2626", "https://d1c5n4ri2guedi.cloudfront.net/card/2626/card_img/31677/2625card_1.png", "['해외 온/오프라인: 3%적립', '네이버 쇼핑: 1.5%적립', '국내 온/오프라인: 0.3%적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 플리 체크(산리오캐릭터즈)", "신한카드", "https://www.card-gorilla.com/card/detail/2492", "https://d1c5n4ri2guedi.cloudfront.net/card/2492/card_img/28476/2492card.png", "['국내 이용금액: 최대 0.3%할인', '해외 이용금액: 0.2%할인', '매 월 2회: 할인쿠폰제공', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "카드의정석 오하CHECK", "우리카드", "https://www.card-gorilla.com/card/detail/2570", "https://d1c5n4ri2guedi.cloudfront.net/card/2570/card_img/38501/2570card.png", "['온라인 쇼핑: 5%캐시백', '간편결제: 5%캐시백', '스타벅스: 5%캐시백', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 SOL트래블 체크", "신한카드", "https://www.card-gorilla.com/card/detail/2667", "https://d1c5n4ri2guedi.cloudfront.net/card/2667/card_img/32473/2660card.png", "['해외 이용: 수수료 면제', '더라운지: 무료입장', '해외 대중교통: 1%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "노리2 체크카드(Global)", "KB국민카드", "https://www.card-gorilla.com/card/detail/2423", "https://d1c5n4ri2guedi.cloudfront.net/card/2423/card_img/27142/2423card.png", "['커피,모바일,문화: 10%할인', '해외 가맹점: 2%할인', '공항라운지: 연 1회이용권', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "NH20해봄체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/362", "https://d1c5n4ri2guedi.cloudfront.net/card/362/card_img/20603/362card.png", "['온라인쇼핑몰: 5%할인', '배달앱: 5%할인', '커피: 20%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "개이득 체크카드", "우체국", "https://www.card-gorilla.com/card/detail/2519", "https://d1c5n4ri2guedi.cloudfront.net/card/2519/card_img/28824/2519card.png", "['국내 전 가맹점: 0.3%캐시백', 'OTT: 30%캐시백', '패션: 30%캐시백', ': 해외겸용 없음', '전월실적: 없음', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 Deep Dream 체크", "신한카드", "https://www.card-gorilla.com/card/detail/281", "https://d1c5n4ri2guedi.cloudfront.net/card/281/card_img/20503/281card.png", "['모두드림: 0.2%적립', '더해드림: 0.6%적립', '챙겨드림: 1.0%적립', ': 해외겸용 없음', '전월실적: 없음', ': VISAUnionPay']"));
        checkCardRepository.save(new CheckCard(null, "토심이 첵첵 체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/2604", "https://d1c5n4ri2guedi.cloudfront.net/card/2604/card_img/31223/2604card.png", "['대중교통: 2~4천원할인', '온라인간편결제: 2~4천원할인', '스타벅스: 2~4천원할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "카카오뱅크 프렌즈 체크카드", "카카오뱅크", "https://www.card-gorilla.com/card/detail/435", "https://d1c5n4ri2guedi.cloudfront.net/card/435/card_img/20935/435card.png", "['국내외 가맹점: 0.2~0.4%캐시백', '학원 업종: 1만원캐시백', '배달의민족: 1천원캐시백', ': 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "탐나는전 체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/1572", "https://d1c5n4ri2guedi.cloudfront.net/card/1572/card_img/22656/1572card.png", "['국내외가맹점: 0.2%기본적립', '주말/공휴일: 0.2%추가적립', '대중교통/택시: 0.2%추가적립', ': 국내전용 없음', '전월실적: 10만원 이상']"));
        checkCardRepository.save(new CheckCard(null, "K-패스카드(체크)", "NH농협카드", "https://www.card-gorilla.com/card/detail/2561", "https://d1c5n4ri2guedi.cloudfront.net/card/2561/card_img/33460/2561card.png", "['대중교통: 10%할인', '렌터카/카쉐어링: 5%할인', '전기차 충전: 5%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "직장인보너스체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/350", "https://d1c5n4ri2guedi.cloudfront.net/card/350/card_img/20594/350card.png", "['국세/지방세: 7,000원할인', 'GS칼텍스: 60~50원/L할인', '백화점: 5%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': VISAMastercard']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 Hey Young 체크", "신한카드", "https://www.card-gorilla.com/card/detail/618", "https://d1c5n4ri2guedi.cloudfront.net/card/618/card_img/21385/618card.png", "['대중교통: 5%캐시백', '영화: 5천원캐시백', '간편결제: 1%캐시백', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "올바른POINT체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/360", "https://d1c5n4ri2guedi.cloudfront.net/card/360/card_img/25852/360card.png", "['전 가맹점: 0.4~0.2%적립', '해외: 0.3%추가적립', '국제공항라운지: 무료이용', ': 해외겸용 없음', '전월실적: 없음', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "춘식이달달체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/2758", "https://d1c5n4ri2guedi.cloudfront.net/card/2758/card_img/37140/2758card_1.png", "['커피·편의점·영화·온라인쇼핑·배달앱: 최대 1%적립', 'OTT: 5%적립', '국제공항 라운지: 무료이용서비스', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "트래블로그 체크카드", "하나카드", "https://www.card-gorilla.com/card/detail/2394", "https://d1c5n4ri2guedi.cloudfront.net/card/2394/card_img/25975/2394card.png", "['해외 가맹점 이용: 수수료면제', '해외 ATM 인출: 수수료면제', '국내가맹점: 0.3%적립', ': 해외겸용 없음', '전월실적: 없음', ': MastercardUnionPay']"));
        checkCardRepository.save(new CheckCard(null, "네이버페이 신한카드 체크 S2", "신한카드", "https://www.card-gorilla.com/card/detail/2268", "https://d1c5n4ri2guedi.cloudfront.net/card/2268/card_img/20698/2268card.png", "['네이버 최대: 2%적립', '네이버 외: 0.1%적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "더 심플 체크카드", "하나카드", "https://www.card-gorilla.com/card/detail/2810", "https://d1c5n4ri2guedi.cloudfront.net/card/2810/card_img/39691/2810card.png", "['통신 요금: 5,000원캐시백', '스타벅스, 커피빈, 투썸플레이스: 5%캐시백', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "K-패스 신한카드 체크", "신한카드", "https://www.card-gorilla.com/card/detail/2693", "https://d1c5n4ri2guedi.cloudfront.net/card/2693/card_img/33495/2692card.png", "['대중교통: 10%할인', '간편결제: 2%할인', '생활 부문: 2%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "나라사랑체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/739", "https://d1c5n4ri2guedi.cloudfront.net/card/739/card_img/22213/739card.png", "['P.X / GS25해군마트 최대: 20%할인', '대중교통: 20%할인', '영화: 35%할인', ': 국내전용 없음', '전월실적: 10만원 이상']"));
        checkCardRepository.save(new CheckCard(null, "달달 하나 체크카드", "하나카드", "https://www.card-gorilla.com/card/detail/2750", "https://d1c5n4ri2guedi.cloudfront.net/card/2750/card_img/36851/2750card_1.png", "['간편결제: 0.3%적립', '쇼핑: 5%적립', '구독: 10%적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': VISAMastercard']"));
        checkCardRepository.save(new CheckCard(null, "모빌리언스카드", "KG모빌리언스", "https://www.card-gorilla.com/card/detail/2321", "https://d1c5n4ri2guedi.cloudfront.net/card/2321/card_img/23849/2321card.png", "['온라인/오프라인 각각: 1%/0.5%적립', '편의점, 커피, 외식 최대: 8%적립', 'KFC: 10%즉시할인', ': 국내전용 없음', '전월실적: 없음']"));
        checkCardRepository.save(new CheckCard(null, "카드의정석 EVERY CHECK", "우리카드", "https://www.card-gorilla.com/card/detail/2552", "https://d1c5n4ri2guedi.cloudfront.net/card/2552/card_img/29589/2552card.png", "['국내외 가맹점: 0.2%적립', '전월실적에 따라: 최대 3천원추가 적립', '공연·테마파크·영화·여행 중 한 곳: 1만원적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "PAYCO 포인트 카드", "엔에이치엔페이코", "https://www.card-gorilla.com/card/detail/2310", "https://d1c5n4ri2guedi.cloudfront.net/card/2310/card_img/37661/2310card.png", "['최대: 1%무한적립', 'AK플라자: 10%상품권 지급', '한게임: 4%적립', ': 해외겸용 없음', '전월실적: 없음', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 On 체크(잔망루피)", "신한카드", "https://www.card-gorilla.com/card/detail/2379", "https://d1c5n4ri2guedi.cloudfront.net/card/2379/card_img/25379/2379card.png", "['간편결제: 2%적립', '생활편의: 2%적립', '해외 이용금액: 1.3%적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "현대카드M CHECK", "현대카드", "https://www.card-gorilla.com/card/detail/407", "https://d1c5n4ri2guedi.cloudfront.net/card/407/card_img/28394/407card.png", "['이용금액별: 1~0.5%적립', ': 국내전용 2,000원', '전월실적: 없음']"));
        checkCardRepository.save(new CheckCard(null, "K-패스체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/2556", "https://d1c5n4ri2guedi.cloudfront.net/card/2556/card_img/33457/2556card.png", "['대중교통: 10%적립', '생활서비스: 1%적립', 'KB Pay 이용 시: 1%추가 적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "청춘대로 싱글 체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/335", "https://d1c5n4ri2guedi.cloudfront.net/card/335/card_img/20579/335card.png", "['편의점: 10~5%할인', '다이소/소셜커머스: 10~5%할인', '동물병원: 10%할인', ': 해외겸용 없음', '전월실적: 30만원 이상', ': MastercardUnionPay']"));
        checkCardRepository.save(new CheckCard(null, "NH 무럭이 체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/2620", "https://d1c5n4ri2guedi.cloudfront.net/card/2620/card_img/31489/2620card.png", "['전가맹점: 0.2%적립', '이용금액 1위: 3배적립', '국제공항 라운지: 무료이용', ': 국내전용 없음', '전월실적: 없음']"));
        checkCardRepository.save(new CheckCard(null, "꿀카드", "MG새마을금고", "https://www.card-gorilla.com/card/detail/2001", "https://d1c5n4ri2guedi.cloudfront.net/card/2001/card_img/21997/2001card.png", "['쿠팡 로켓와우 최대: 2,900원할인', 'OTT 서비스: 2천원할인', '음원 스트리밍: 1천원할인', ': 국내전용 없음', '전월실적: 없음', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "위비트래블 체크카드", "우리카드", "https://www.card-gorilla.com/card/detail/2700", "https://d1c5n4ri2guedi.cloudfront.net/card/2700/card_img/34201/2700card.png", "['해외: 5%캐시백', '푸드: 5%캐시백', '해외 가맹점: 이용 수수료면제', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "올바른 NEW HAVE체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/1765", "https://d1c5n4ri2guedi.cloudfront.net/card/1765/card_img/22348/1765card.png", "['국내외가맹점: 0.2%적립', '이용금액1위: 3배적립', '국제공항라운지: 무료아용', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "신한 후불 기후동행 체크카드", "신한카드", "https://www.card-gorilla.com/card/detail/2767", "https://d1c5n4ri2guedi.cloudfront.net/card/2767/card_img/38057/2767card.png", "['온라인: 5%할인', '오프라인: 5%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "라이언 치즈 체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/528", "https://d1c5n4ri2guedi.cloudfront.net/card/528/card_img/21216/528card.png", "['커피: 최대 1%적립', '대중교통: 1.5%적립', '유튜브결제: 5%적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': UnionPay']"));
        checkCardRepository.save(new CheckCard(null, "KB국민 기후동행체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/2770", "https://d1c5n4ri2guedi.cloudfront.net/card/2770/card_img/38060/2770card.png", "['커피, 편의점, 약국, 패스트푸드: 2%할인', 'KB Pay, 올리브영: 5%할인', '영화: 5%할인', ': 국내전용 없음', '전월실적: 없음']"));
        checkCardRepository.save(new CheckCard(null, "올리 POINT 체크", "NH농협카드", "https://www.card-gorilla.com/card/detail/676", "https://d1c5n4ri2guedi.cloudfront.net/card/676/card_img/21441/676card.png", "['국내외가맹점: 0.2%기본적립', '1~2위 이용영역: 2~3배적립', '공항라운지: 무료이용', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "케이뱅크 플러스 체크카드", "케이뱅크", "https://www.card-gorilla.com/card/detail/669", "https://d1c5n4ri2guedi.cloudfront.net/card/669/card_img/21434/669card.png", "['모든가맹점: 0.3%캐시백', 'ATM수수료: 무료서비스', '언택트 업종: 3%특별캐시백', ': 해외겸용 없음', '전월실적: 없음', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "그랑블루 체크카드", "우리카드", "https://www.card-gorilla.com/card/detail/325", "https://d1c5n4ri2guedi.cloudfront.net/card/325/card_img/20570/325card.png", "['모아포인트: 0.3~1.0%적립', '기프트바우처: 연1회제공', '공항라운지: 무료이용', ': 해외겸용 95,000원', '전월실적: 30만원 이상', ': BCBC GlobalMastercard']"));
        checkCardRepository.save(new CheckCard(null, "가온 올포인트 체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/454", "https://d1c5n4ri2guedi.cloudfront.net/card/454/card_img/20970/454card.png", "['국내외 가맹점: 0.2%기본적립', '대형마트: 0.8%추가적립', 'GS칼텍스: 0.8%추가적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 10만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "트래블GO 체크카드", "하나카드", "https://www.card-gorilla.com/card/detail/2740", "https://d1c5n4ri2guedi.cloudfront.net/card/2740/card_img/36648/2740card_1.png", "['해외 가맹점 수수료: 건당 $0.5면제', '해외 ATM 인출 수수료: 건당 $3면제', '국내 가맹점: 최대 5%적립', ': 해외겸용 없음', '전월실적: 20만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "행복한 체크카드", "우체국", "https://www.card-gorilla.com/card/detail/585", "https://d1c5n4ri2guedi.cloudfront.net/card/585/card_img/21340/585card.png", "['마트: 10%캐시백', '병·의원/약국: 10%캐시백', '학원: 10%캐시백', ': 해외겸용 없음', '전월실적: 30만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "K-패스 삼성체크카드", "삼성카드", "https://www.card-gorilla.com/card/detail/2563", "https://d1c5n4ri2guedi.cloudfront.net/card/2563/card_img/29688/2563card.png", "['대중교통: 10%캐시백', '이동통신: 10%캐시백', '편의점/커피전문점/제과: 1,000원캐시백', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상']"));
        checkCardRepository.save(new CheckCard(null, "스타플러스 체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/2588", "https://d1c5n4ri2guedi.cloudfront.net/card/2588/card_img/30834/2588card.png", "['커피·모바일·문화: 10%할인', '뷰티·편의점: 5%할인', '공항라운지: 연 1회제공', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "IBK무민카드(체크)", "IBK기업은행", "https://www.card-gorilla.com/card/detail/674", "https://d1c5n4ri2guedi.cloudfront.net/card/674/card_img/21439/674card.png", "['대중교통: 건당100원할인', '온라인쇼핑: 10%할인', '커피전문점: 10%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상', ': BCUnionPay']"));
        checkCardRepository.save(new CheckCard(null, "KB국민 우리동네 체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/2332", "https://d1c5n4ri2guedi.cloudfront.net/card/2332/card_img/24588/2332card.png", "['세탁소, 정육점: 10%할인', '슈퍼마켓: 5%할인', '번개장터: 5%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': VISAUnionPay']"));
        checkCardRepository.save(new CheckCard(null, "NH트래블리체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/2727", "https://d1c5n4ri2guedi.cloudfront.net/card/2727/card_img/36095/2727_1card.png", "['해외가맹점: 해외이용수수료면제', '국내 가맹점: 0.2~0.3% 캐시백무제한', '일상 가맹점: 0.6% 캐시백무제한', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 Way 체크", "신한카드", "https://www.card-gorilla.com/card/detail/2338", "https://d1c5n4ri2guedi.cloudfront.net/card/2338/card_img/24301/2338card.png", "['대중교통: 5%적립', '생활편의: 2%적립', '해외 이용금액: 1.3%적립', ': 국내전용 없음 해외겸용없음', '전월실적: 20만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "카카오페이 체크카드", "MG새마을금고", "https://www.card-gorilla.com/card/detail/2094", "https://d1c5n4ri2guedi.cloudfront.net/card/2094/card_img/21906/2094card.png", "['카카오페이: 15%할인', '편의점: 5%할인', '온라인쇼핑: 10%할인', ': 국내전용 없음', '전월실적: 15만원 이상']"));
        checkCardRepository.save(new CheckCard(null, "카드의정석 EVERYDAY CHECK", "우리카드", "https://www.card-gorilla.com/card/detail/2742", "https://d1c5n4ri2guedi.cloudfront.net/card/2742/card_img/36729/2742card.png", "['국내/해외 가맹점: 0.2%적립', '우리페이: 0.5%추가 적립', '마트/슈퍼/커피/주유: 1%특별 적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "영리한 PLUS 체크카드", "우체국", "https://www.card-gorilla.com/card/detail/2227", "https://d1c5n4ri2guedi.cloudfront.net/card/2227/card_img/21354/2227card.png", "['디지털콘텐츠: 20%캐시백', '온라인쇼핑: 15%캐시백', '배달앱: 15%캐시백', ': 해외겸용 없음', '전월실적: 30만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "내일배움체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/367", "https://d1c5n4ri2guedi.cloudfront.net/card/367/card_img/20608/367card.png", "['주유소: 40원/L할인', '서적: 10%할인', '커피: 10%할인', ': 국내전용 없음', '전월실적: 없음']"));
        checkCardRepository.save(new CheckCard(null, "우리 기후동행카드(체크)", "우리카드", "https://www.card-gorilla.com/card/detail/2826", "https://d1c5n4ri2guedi.cloudfront.net/card/2826/card_img/39936/2826card.png", "['올리브영, 다이소: 5%캐시백', '교보문고: 5%캐시백', '어학원(해커스/파고다): 5%캐시백', ': 국내전용 없음', '전월실적: 25만원 이상', ': BC']"));
        checkCardRepository.save(new CheckCard(null, "K-패스(체크)", "IBK기업은행", "https://www.card-gorilla.com/card/detail/2562", "https://d1c5n4ri2guedi.cloudfront.net/card/2562/card_img/33444/2526card.png", "['대중교통: 건당 100원할인', '커피: 10%할인', '쇼핑: 10%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "케이뱅크 X KT멤버십더블혜택 체크카드", "케이뱅크", "https://www.card-gorilla.com/card/detail/436", "https://d1c5n4ri2guedi.cloudfront.net/card/436/card_img/20937/436card.png", "['KT통신요금: 20~5%캐시백', 'KT멤버십: 더블할인', '해외이용: 수수료면제', ': 해외겸용 없음', '전월실적: 20만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "삼성체크카드 & CASHBACK", "삼성카드", "https://www.card-gorilla.com/card/detail/394", "https://d1c5n4ri2guedi.cloudfront.net/card/394/card_img/28057/394card.png", "['0.6~0.2%: 캐시백제공', '놀이공원: 50%할인', 'CGV: 3,000원할인', ': 국내전용 없음', '전월실적: 없음']"));
        checkCardRepository.save(new CheckCard(null, "K-패스 하나 체크카드", "하나카드", "https://www.card-gorilla.com/card/detail/2682", "https://d1c5n4ri2guedi.cloudfront.net/card/2682/card_img/33462/2682card.png", "['대중교통: 10%캐시백', '드럭스토어: 1%캐시백', '커피: 1%캐시백', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "NH올원체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/368", "https://d1c5n4ri2guedi.cloudfront.net/card/368/card_img/20609/368card.jpg", "['실적관계없이: 0.4~0.2%적립', '해외이용액: 0.4%적립', 'OK캐시백: 포인트적립', ': 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "NEW농촌사랑체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/497", "https://d1c5n4ri2guedi.cloudfront.net/card/497/card_img/21186/497card.png", "['NH포인트: 최대0.5%적립', 'GS칼텍스: 40원/L할인', '놀이공원: 연6회할인', ': 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "어디서나 체크카드", "우체국", "https://www.card-gorilla.com/card/detail/571", "https://d1c5n4ri2guedi.cloudfront.net/card/571/card_img/21304/571card.png", "['마트: 5%캐시백', '소셜커머스: 5%캐시백', '음식점: 5%적립', ': 해외겸용 없음', '전월실적: 30만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/499", "https://d1c5n4ri2guedi.cloudfront.net/card/499/card_img/21188/499card.png", "['농협판매장: 5%적립', '주유소: 40원/L할인', '영화: 10%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "IBK 나라사랑카드", "IBK기업은행", "https://www.card-gorilla.com/card/detail/446", "https://d1c5n4ri2guedi.cloudfront.net/card/446/card_img/20952/446card.png", "['대중교통: 10%할인', '철도/고속버스: 5%할인', 'CU: 5%현장할인', ': 국내전용 없음', '전월실적: 8만원 이상', ': BC']"));
        checkCardRepository.save(new CheckCard(null, "롯데체크카드", "롯데카드", "https://www.card-gorilla.com/card/detail/403", "https://d1c5n4ri2guedi.cloudfront.net/card/403/card_img/20901/403card.png", "['전국 가맹점: 0.2%L.POINT 적립', 'SK주유소: 50P/L주유포인트 적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "현대카드M HYBRID", "현대카드", "https://www.card-gorilla.com/card/detail/414", "https://d1c5n4ri2guedi.cloudfront.net/card/414/card_img/28396/414card.png", "['이용금액별: 1~0.5%적립', ': 국내전용 없음', '전월실적: 없음']"));
        checkCardRepository.save(new CheckCard(null, "하나 기후동행체크카드", "하나카드", "https://www.card-gorilla.com/card/detail/2768", "https://d1c5n4ri2guedi.cloudfront.net/card/2768/card_img/38058/2768card.png", "['편의점: 1,000원캐시백', '서점: 1,000원캐시백', '베이커리: 1,000원캐시백', ': 국내전용 없음', '전월실적: 10만원 이상']"));
        checkCardRepository.save(new CheckCard(null, "카카오페이 체크카드", "하나카드", "https://www.card-gorilla.com/card/detail/382", "https://d1c5n4ri2guedi.cloudfront.net/card/382/card_img/20882/382card.png", "['카카오페이: 7%캐시백', '대중교통: 5%캐시백', '스타벅스: 5%캐시백', ': 해외겸용 없음', '전월실적: 25만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "미래에셋증권 체크카드(할인 2)", "미래에셋증권", "https://www.card-gorilla.com/card/detail/2216", "https://d1c5n4ri2guedi.cloudfront.net/card/2216/card_img/21769/2216card.png", "['커피전문점: 10%할인', '편의점: 10%할인', '디지털구독 건당: 5,000원할인', ': 국내전용 없음', '전월실적: 30만원 이상']"));
        checkCardRepository.save(new CheckCard(null, "기후동행카드(체크)", "NH농협카드", "https://www.card-gorilla.com/card/detail/2773", "https://d1c5n4ri2guedi.cloudfront.net/card/2773/card_img/38079/2773card.png", "['온라인쇼핑몰: 5%할인', '이동통신 자동납부: 2,500원할인', '커피: 10%할인', ': 국내전용 없음', '전월실적: 20만원 이상']"));
        checkCardRepository.save(new CheckCard(null, "able Premier Members 카드", "KB증권", "https://www.card-gorilla.com/card/detail/2225", "https://d1c5n4ri2guedi.cloudfront.net/card/2225/card_img/21356/2225card.png", "['한도없이: 0.5%캐시백', '호텔 최대: 50%할인', ': 국내전용 없음', '전월실적: 없음']"));
        checkCardRepository.save(new CheckCard(null, "BAZIC(베이직)체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/370", "https://d1c5n4ri2guedi.cloudfront.net/card/370/card_img/20867/370card.png", "['국내외 전 가맹점: 0.3~0.2%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 주거래 체크", "신한카드", "https://www.card-gorilla.com/card/detail/284", "https://d1c5n4ri2guedi.cloudfront.net/card/284/card_img/20506/284card.png", "['전가맹점: 0.3%적립', '쇼핑, 해외가맹점: 0.7%추가적립', '생활가맹점: 1.7%추가적립', ': 해외겸용 없음', '전월실적: 30만원 이상', ': VISAUnionPay']"));
        checkCardRepository.save(new CheckCard(null, "노리2 체크카드(Play)", "KB국민카드", "https://www.card-gorilla.com/card/detail/2550", "https://d1c5n4ri2guedi.cloudfront.net/card/2550/card_img/29586/2550card.png", "['커피·모바일·문화: 10%할인', '뷰티·편의점: 5%할인', '에버랜드·롯데월드: 15,000원할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "민 체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/346", "https://d1c5n4ri2guedi.cloudfront.net/card/346/card_img/20591/346card.png", "['대형마트: 5%할인', 'SK에너지: 60원/L할인', '대중교통: 5%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상', ': VISAMastercard']"));
        checkCardRepository.save(new CheckCard(null, "올바른GLOBAL체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/375", "https://d1c5n4ri2guedi.cloudfront.net/card/375/card_img/20874/375card.png", "['해외구매시: 2%캐시백', '국제공항라운지: 무료이용', '10대업종: 1.0~0.5%캐시백', ': 해외겸용 없음', '전월실적: 20만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "브라보(Bravo) 체크카드", "우체국", "https://www.card-gorilla.com/card/detail/2628", "https://d1c5n4ri2guedi.cloudfront.net/card/2628/card_img/31739/2628card.png", "['모든 음식점: 5%캐시백', '롯데마트・이마트・홈플러스: 5%캐시백', '전기차 충전: 5%캐시백', ': 해외겸용 없음', '전월실적: 30만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "에어머니 체크카드", "MG새마을금고", "https://www.card-gorilla.com/card/detail/2509", "https://d1c5n4ri2guedi.cloudfront.net/card/2509/card_img/28715/2509card.png", "['Air Money: 0.3%적립', '여행·관광 업종: 3,000원특별적립', '국내 공항 라운지: 무료이용', ': 해외겸용 없음', '전월실적: 10만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "FANtastic S 신한카드 체크", "신한카드", "https://www.card-gorilla.com/card/detail/278", "https://d1c5n4ri2guedi.cloudfront.net/card/278/card_img/20500/278card.png", "['간편결제(FAN페이): 15%캐시백', '쿠팡,티몬: 10%캐시백', '스타벅스: 10%캐시백', ': 해외겸용 없음', '전월실적: 30만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "새로이 체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/725", "https://d1c5n4ri2guedi.cloudfront.net/card/725/card_img/22199/725card.png", "['편의점: 5%할인', '이동통신요금: 5%할인', '정기구독: 5%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상', ': UnionPay']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 Pick E 체크", "신한카드", "https://www.card-gorilla.com/card/detail/2528", "https://d1c5n4ri2guedi.cloudfront.net/card/2528/card_img/28966/2528card.png", "['편의점·커피: 10%적립', '사진·볼링·테니스·스키: 10%적립', 'One Pick 맛집: 3천 포인트적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "카카오뱅크 개인사업자 체크카드", "카카오뱅크", "https://www.card-gorilla.com/card/detail/2421", "https://d1c5n4ri2guedi.cloudfront.net/card/2421/card_img/27093/2421card.png", "['생활업종: 0.3%캐시백', '사업업종: 3%캐시백', ': 국내전용 없음 해외겸용 없음', '전월실적: 없음', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "어피치 스윗 체크카드", "NH농협카드", "https://www.card-gorilla.com/card/detail/586", "https://d1c5n4ri2guedi.cloudfront.net/card/586/card_img/21342/586card.png", "['온라인 간편결제: 3%할인', '카페: 4%할인', '넷플릭스: 5%할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상', ': UnionPay']"));
        checkCardRepository.save(new CheckCard(null, "iM K-패스 체크카드", "iM뱅크", "https://www.card-gorilla.com/card/detail/2817", "https://d1c5n4ri2guedi.cloudfront.net/card/2817/card_img/39840/2817card.png", "['대중교통: 10%할인', '배달앱: 2%할인', '이동통신: 2%할인', ': 국내전용 없음', '전월실적: 20만원 이상', ': BC']"));
        checkCardRepository.save(new CheckCard(null, "당근머니 하나 체크카드", "하나카드", "https://www.card-gorilla.com/card/detail/2721", "https://d1c5n4ri2guedi.cloudfront.net/card/2721/card_img/35850/2720card_1.png", "['지역 가맹점: 3.0%적립', '당근 앱 내 결제: 5.0%적립', '국내 전 가맹점: 0.5%적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상', ': Mastercard']"));
        checkCardRepository.save(new CheckCard(null, "신한 S-Choice체크카드", "신한카드", "https://www.card-gorilla.com/card/detail/296", "https://d1c5n4ri2guedi.cloudfront.net/card/296/card_img/20519/296card.gif", "['버스/지하철/택시: 10%할인(캐시백)', '커피전문점: 20%할인(캐시백)', '백화점: 10%할인(캐시백)', ': 해외겸용 없음', '전월실적: 20만원 이상', ': VISAMastercard']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 On 체크", "신한카드", "https://www.card-gorilla.com/card/detail/2343", "https://d1c5n4ri2guedi.cloudfront.net/card/2343/card_img/24358/2343card.png", "['간편결제: 2%적립', '생활편의: 2%적립', '해외 이용금액: 1.3%적립', ': 국내전용 없음 해외겸용 없음', '전월실적: 20만원 이상', ': VISA']"));
        checkCardRepository.save(new CheckCard(null, "현대카드X CHECK", "현대카드", "https://www.card-gorilla.com/card/detail/408", "https://d1c5n4ri2guedi.cloudfront.net/card/408/card_img/28395/408card.png", "['사용금액별: 0.6~0.3%적립', ': 국내전용 2,000원', '전월실적: 없음']"));
        checkCardRepository.save(new CheckCard(null, "카카오페이 신한 체크카드(무지)", "신한카드", "nan", "https://d1c5n4ri2guedi.cloudfront.net/card/474/card_img/21164/474card.png", "[]"));
        checkCardRepository.save(new CheckCard(null, "able 카드 Ⅱ", "KB증권", "https://www.card-gorilla.com/card/detail/2219", "https://d1c5n4ri2guedi.cloudfront.net/card/2219/card_img/21765/2219card.png", "['대형마트: 5%할인', '배달앱: 5%할인', '주유시 리터당: 40원할인', ': 국내전용 없음', '전월실적: 30만원 이상']"));
        checkCardRepository.save(new CheckCard(null, "신한카드 하이패스(전용) 체크", "신한카드", "https://www.card-gorilla.com/card/detail/391", "https://d1c5n4ri2guedi.cloudfront.net/card/391/card_img/20890/391card.png", "['하이패스요금: 0.1%적립', '통행료: 20%자동할인', ': 국내전용 없음', '전월실적: 10만원 이상']"));
        checkCardRepository.save(new CheckCard(null, "위글위글 첵첵 체크카드", "KB국민카드", "https://www.card-gorilla.com/card/detail/614", "https://d1c5n4ri2guedi.cloudfront.net/card/614/card_img/21381/614card.png", "['네이버페이,카카오페이: 2~4천원할인', '스타벅스: 2~4천원할인', '텐바이텐: 2~4천원할인', ': 국내전용 없음 해외겸용 없음', '전월실적: 30만원 이상', ': VISA']"));
    }
} 