spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:demo}
      username: ${MONGODB_USERNAME:}
      password: ${MONGODB_PASSWORD:}

server:
  port: ${SERVER_PORT:8080} 