spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.example.demo: DEBUG 