spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: INFO
    com.example.demo: INFO 