name: Deploy to EC2

# main 브랜치에 푸시될 때 실행
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. EC2로 파일 전송
      - name: Copy backend files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: backend/
          target: /home/ubuntu/
          strip_components: 1
          timeout: 600s           # 타임아웃 시간 증가 (10분)
          command_timeout: 30m    # 명령어 타임아웃 증가
          proxy_timeout: 180s     # 프록시 타임아웃 증가
          retries: 3             # 연결 재시도 횟수

      # 3. EC2에서 명령어 실행
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 30m    # SSH 명령어 타임아웃 증가
          script_stop: true      # 스크립트 실행 중 에러 발생 시 중지
          script: |
            cd ~/backend
            docker-compose -f docker-compose.aws.yml down
            docker-compose -f docker-compose.aws.yml up -d --build
